# Generated by Django 6.1 on 2026-09-02 01:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Brand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, unique=True, verbose_name='Nome da Marca')),
                ('slug', models.SlugField(blank=True, max_length=160, unique=True, verbose_name='Slug')),
                ('logo', models.ImageField(blank=True, null=True, upload_to='brands/', verbose_name='Logo')),
                ('description', models.TextField(blank=True, verbose_name='Descrição / Estilo')),
                ('website', models.URLField(blank=True, verbose_name='Site / Redes')),
                ('is_active', models.BooleanField(default=True, verbose_name='Ativa')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
            ],
            options={
                'verbose_name': 'Marca',
                'verbose_name_plural': 'Marcas',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Drop',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150, verbose_name='Título do Drop')),
                ('slug', models.SlugField(blank=True, max_length=160, unique=True, verbose_name='Slug')),
                ('edition', models.CharField(blank=True, help_text='Ex: DROP-2026-W36-01', max_length=50, verbose_name='Edição / Código')),
                ('launch_date', models.DateField(verbose_name='Data de Lançamento')),
                ('banner', models.ImageField(blank=True, null=True, upload_to='drops/', verbose_name='Banner Promocional')),
                ('description', models.TextField(blank=True, verbose_name='Conceito & Curadoria')),
                ('is_featured', models.BooleanField(default=False, verbose_name='Destaque na Home')),
                ('is_active', models.BooleanField(default=True, verbose_name='Ativo')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
            ],
            options={
                'verbose_name': 'Drop Semanal',
                'verbose_name_plural': 'Drops Semanais',
                'ordering': ['-launch_date'],
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nome da Categoria')),
                ('slug', models.SlugField(blank=True, max_length=120, unique=True, verbose_name='Slug')),
                ('gender_target', models.CharField(choices=[('F', 'Feminino'), ('M', 'Masculino'), ('U', 'Unissex')], default='U', max_length=1, verbose_name='Público-Alvo')),
                ('icon', models.CharField(blank=True, default='solar:t-shirt-bold-duotone', max_length=50, verbose_name='Ícone (Classe CSS/Solar)')),
                ('is_active', models.BooleanField(default=True, verbose_name='Ativa')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Ordem de Exibição')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='children', to='catalog.category', verbose_name='Categoria Pai')),
            ],
            options={
                'verbose_name': 'Categoria',
                'verbose_name_plural': 'Categorias',
                'ordering': ['order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Nome da Peça')),
                ('slug', models.SlugField(blank=True, max_length=220, unique=True, verbose_name='Slug')),
                ('gender', models.CharField(choices=[('F', 'Feminino'), ('M', 'Masculino'), ('U', 'Unissex')], default='F', max_length=1, verbose_name='Gênero')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Preço de Venda (R$)')),
                ('compare_at_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Preço Original / De (R$)')),
                ('cost_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Preço de Custo (R$)')),
                ('description', models.TextField(blank=True, verbose_name='Descrição da Peça')),
                ('fabric_composition', models.CharField(blank=True, help_text='Ex: 100% Algodão Pima / Linho Puro', max_length=255, verbose_name='Composição do Tecido')),
                ('care_instructions', models.TextField(blank=True, verbose_name='Instruções de Lavagem')),
                ('is_exclusive', models.BooleanField(default=True, verbose_name='Peça Exclusiva / Limitada')),
                ('is_featured', models.BooleanField(default=False, verbose_name='Destaque')),
                ('is_active', models.BooleanField(default=True, verbose_name='Ativo no Catálogo')),
                ('views_count', models.PositiveIntegerField(default=0, verbose_name='Visualizações')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('brand', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='products', to='catalog.brand', verbose_name='Marca')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='products', to='catalog.category', verbose_name='Categoria')),
                ('drop', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='products', to='catalog.drop', verbose_name='Drop da Semana')),
            ],
            options={
                'verbose_name': 'Produto',
                'verbose_name_plural': 'Produtos',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ProductImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to='products/', verbose_name='Arquivo de Imagem')),
                ('image_url', models.URLField(blank=True, null=True, verbose_name='URL Externa (CDN/Cloud)')),
                ('alt_text', models.CharField(blank=True, max_length=200, verbose_name='Texto Alternativo (Acessibilidade/SEO)')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Ordem')),
                ('is_cover', models.BooleanField(default=False, verbose_name='Foto de Capa Principal')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='catalog.product', verbose_name='Produto')),
            ],
            options={
                'verbose_name': 'Imagem do Produto',
                'verbose_name_plural': 'Imagens do Produto',
                'ordering': ['order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='ProductVariant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('size', models.CharField(help_text='Ex: PP, P, M, G, GG, 38, 40, 42, etc.', max_length=30, verbose_name='Tamanho')),
                ('color', models.CharField(blank=True, max_length=50, verbose_name='Cor / Estampa')),
                ('color_hex', models.CharField(blank=True, help_text='Ex: #000000, #F5F5DC', max_length=10, verbose_name='Cor HEX')),
                ('sku', models.CharField(max_length=60, unique=True, verbose_name='SKU / Código')),
                ('stock_quantity', models.PositiveIntegerField(default=1, verbose_name='Quantidade em Estoque')),
                ('additional_price', models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='Acréscimo de Preço (R$)')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='variants', to='catalog.product', verbose_name='Produto')),
            ],
            options={
                'verbose_name': 'Variação de Produto',
                'verbose_name_plural': 'Variações de Produtos',
                'unique_together': {('product', 'size', 'color')},
            },
        ),
    ]
