# Generated by Django 6.1 on 2026-09-02 03:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CarouselSlide',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Título do Slide')),
                ('subtitle', models.TextField(blank=True, verbose_name='Subtítulo / Descrição')),
                ('badge_text', models.CharField(blank=True, help_text='Ex: ✨ Drop Feminino Ativo', max_length=100, verbose_name='Texto da Tag / Badge')),
                ('image', models.ImageField(blank=True, null=True, upload_to='carousels/', verbose_name='Imagem do Banner')),
                ('image_url', models.URLField(blank=True, verbose_name='URL da Imagem (Opcional / CDN)')),
                ('button_text', models.CharField(default='Explorar Coleção', max_length=60, verbose_name='Texto do Botão')),
                ('button_url', models.CharField(default='/produtos/', max_length=255, verbose_name='Link de Destino')),
                ('slide_type', models.CharField(choices=[('hero', 'Hero Principal (Topo da Home)'), ('drops', 'Drops & Novidades da Semana'), ('promo', 'Banner Promocional')], default='hero', max_length=20, verbose_name='Posição / Tipo')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Ordem de Exibição')),
                ('is_active', models.BooleanField(default=True, verbose_name='Ativo no Site')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
            ],
            options={
                'verbose_name': 'Slide do Carrossel',
                'verbose_name_plural': 'Slides dos Carrosséis',
                'ordering': ['slide_type', 'order', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='LinktreeItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=120, verbose_name='Título do Botão')),
                ('subtitle', models.CharField(blank=True, max_length=150, verbose_name='Subtítulo Curto (Opcional)')),
                ('url', models.CharField(max_length=500, verbose_name='URL de Destino')),
                ('icon', models.CharField(default='bx bx-link-external', help_text='Ex: bx bxl-whatsapp, bx bxl-instagram, bx bx-map-pin, bx bx-shopping-bag', max_length=60, verbose_name='Ícone (Boxicons/Solar)')),
                ('style', models.CharField(choices=[('dark', 'Preto Elegante (Padrão)'), ('gold', 'Dourado / Bronze (Destaque VIP)'), ('success', 'Verde WhatsApp (Conversão)'), ('outline', 'Borda Fina Minimalista')], default='dark', max_length=20, verbose_name='Estilo Visual')),
                ('is_highlighted', models.BooleanField(default=False, verbose_name='Destacar com Animação')),
                ('is_active', models.BooleanField(default=True, verbose_name='Visível no Linktree')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Ordem de Exibição')),
                ('clicks_count', models.PositiveIntegerField(default=0, verbose_name='Total de Cliques')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
            ],
            options={
                'verbose_name': 'Link do Linktree',
                'verbose_name_plural': 'Links do Linktree',
                'ordering': ['order', 'id'],
            },
        ),
    ]
