# Generated by Django 6.1 on 2026-09-04 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_carouselslide_linktreeitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='productimage',
            name='color',
            field=models.CharField(blank=True, help_text='Cor associada a esta foto (opcional)', max_length=50, verbose_name='Cor / Variação Vinculada'),
        ),
    ]
