# Generated by Django 6.1 on 2026-09-04 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0003_productimage_color'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='linktreeitem',
            options={'ordering': ['page_type', 'order', 'id'], 'verbose_name': 'Link do Linktree', 'verbose_name_plural': 'Links do Linktree'},
        ),
        migrations.AddField(
            model_name='linktreeitem',
            name='page_type',
            field=models.CharField(choices=[('vakaria', 'Vakaria Barbearia (/links)'), ('luiza_fit', 'Luiza Fit Moda Fitness (/tree)')], default='vakaria', max_length=20, verbose_name='Página do Linktree'),
        ),
        migrations.AlterField(
            model_name='linktreeitem',
            name='style',
            field=models.CharField(choices=[('dark', 'Preto Elegante (Padrão)'), ('gold', 'Dourado / Champagne (Destaque VIP)'), ('success', 'Verde WhatsApp (Conversão)'), ('rose', 'Rosa Luiza Fit (Moda Feminina)'), ('champagne', 'Champagne Glamour'), ('outline', 'Borda Fina Minimalista')], default='dark', max_length=20, verbose_name='Estilo Visual'),
        ),
    ]
