# Generated by Django 6.1 on 2026-09-04 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0004_alter_linktreeitem_options_linktreeitem_page_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productvariant',
            name='sku',
            field=models.CharField(blank=True, max_length=60, unique=True, verbose_name='SKU / Código'),
        ),
    ]
