# Generated by Django 6.1 on 2026-09-04 22:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0005_alter_productvariant_sku'),
    ]

    operations = [
        migrations.CreateModel(
            name='HomePageConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('announcement_active', models.BooleanField(default=True, verbose_name='Exibir Barra de Avisos no Topo')),
                ('announcement_text', models.CharField(default='✨ Drops & Novidades 2x por semana • Cajazeiras - PB e envio para todo o Brasil', max_length=255, verbose_name='Texto do Aviso')),
                ('announcement_badge', models.CharField(blank=True, default='NOVIDADES', max_length=50, verbose_name='Tag / Badge do Aviso')),
                ('announcement_link', models.CharField(blank=True, default='/produtos/', max_length=255, verbose_name='Link de Destino do Aviso')),
                ('women_card_image', models.ImageField(blank=True, null=True, upload_to='home/cards/', verbose_name='Foto do Card Feminino')),
                ('women_card_image_url', models.URLField(blank=True, default='https://images.unsplash.com/photo-1483985988355-763728e1935b?auto=format&fit=crop&w=1000&q=80', verbose_name='URL da Foto Feminina (Fallback/CDN)')),
                ('women_card_badge', models.CharField(default='👗 Coleção Feminina', max_length=60, verbose_name='Badge Card Feminino')),
                ('women_card_title', models.CharField(default='Moda Feminina Autêntica', max_length=120, verbose_name='Título Card Feminino')),
                ('women_card_subtitle', models.TextField(default='Vestidos de seda, conjuntos de alfaiataria, linho puro e novidades semanais.', verbose_name='Descrição Card Feminino')),
                ('women_card_url', models.CharField(default='/produtos/?gender=F', max_length=255, verbose_name='Link Card Feminino')),
                ('women_card_btn_text', models.CharField(default='Ver Coleção Feminina', max_length=60, verbose_name='Texto do Botão Feminino')),
                ('men_card_image', models.ImageField(blank=True, null=True, upload_to='home/cards/', verbose_name='Foto do Card Masculino')),
                ('men_card_image_url', models.URLField(blank=True, default='https://images.unsplash.com/photo-1507679799987-c73779587ccf?auto=format&fit=crop&w=1000&q=80', verbose_name='URL da Foto Masculina (Fallback/CDN)')),
                ('men_card_badge', models.CharField(default='👔 Coleção Masculina', max_length=60, verbose_name='Badge Card Masculino')),
                ('men_card_title', models.CharField(default='Moda Masculina Elegante', max_length=120, verbose_name='Título Card Masculino')),
                ('men_card_subtitle', models.TextField(default='Camisas em linho nobre, blazers slim, polos pima cotton e bermudas alfaiataria.', verbose_name='Descrição Card Masculino')),
                ('men_card_url', models.CharField(default='/produtos/?gender=M', max_length=255, verbose_name='Link Card Masculino')),
                ('men_card_btn_text', models.CharField(default='Ver Coleção Masculina', max_length=60, verbose_name='Texto do Botão Masculino')),
                ('store_image', models.ImageField(blank=True, null=True, upload_to='home/store/', verbose_name='Foto da Loja Física')),
                ('store_image_url', models.URLField(blank=True, default='https://images.unsplash.com/photo-1441986300917-64674bd600d8?auto=format&fit=crop&w=1000&q=80', verbose_name='URL da Foto da Loja (Fallback/CDN)')),
                ('store_badge', models.CharField(default='📍 Loja Física em Cajazeiras - PB', max_length=100, verbose_name='Badge Seção Loja')),
                ('store_title', models.CharField(default='Experiência Presencial na Vakaria', max_length=150, verbose_name='Título Seção Loja')),
                ('store_description', models.TextField(default='Localizada no centro de Cajazeiras, nossa loja física foi criada para proporcionar conforto, sofisticação e uma experiência de compra personalizada. Venha conhecer de perto as peças, experimentar as composições e tomar um café com a nossa equipe.', verbose_name='Descrição Seção Loja')),
                ('store_address', models.CharField(default='Rua José Pires Braga 120, Cajazeiras PB, 58900-000, Brasil', max_length=255, verbose_name='Endereço Completo')),
                ('store_phone', models.CharField(default='+55 81 8398-3355', max_length=50, verbose_name='WhatsApp & Telefone de Vendas')),
                ('store_instagram_handle', models.CharField(default='@eduardo_vaka_', max_length=60, verbose_name='Instagram Handle')),
                ('store_maps_url', models.CharField(default='https://maps.google.com/?q=Rua+Jose+Pires+Braga+120+Cajazeiras+PB', max_length=500, verbose_name='Link do Google Maps')),
                ('store_status_badge', models.CharField(default='Loja Aberta', max_length=50, verbose_name='Badge de Status da Loja')),
                ('drops_badge', models.CharField(default='🔥 Lançamentos Recentes', max_length=80, verbose_name='Badge da Seção Drops')),
                ('drops_title', models.CharField(default='Drops & Novidades da Semana', max_length=120, verbose_name='Título da Seção Drops')),
                ('drops_subtitle', models.CharField(default='Novidades exclusivas que chegam duas vezes por semana na loja.', max_length=200, verbose_name='Subtítulo da Seção Drops')),
                ('benefit1_icon', models.CharField(default='solar:refresh-circle-bold-duotone', max_length=60, verbose_name='Ícone Vantagem 1')),
                ('benefit1_title', models.CharField(default='Drops 2x por Semana', max_length=80, verbose_name='Título Vantagem 1')),
                ('benefit1_subtitle', models.CharField(default='Novidades terças e quintas', max_length=120, verbose_name='Subtítulo Vantagem 1')),
                ('benefit2_icon', models.CharField(default='solar:tag-bold-duotone', max_length=60, verbose_name='Ícone Vantagem 2')),
                ('benefit2_title', models.CharField(default='Curadoria Multimarcas', max_length=80, verbose_name='Título Vantagem 2')),
                ('benefit2_subtitle', models.CharField(default='Os melhores produtos e atendimento da região', max_length=120, verbose_name='Subtítulo Vantagem 2')),
                ('benefit3_icon', models.CharField(default='solar:chat-round-dots-bold-duotone', max_length=60, verbose_name='Ícone Vantagem 3')),
                ('benefit3_title', models.CharField(default='Personal Stylist VIP', max_length=80, verbose_name='Título Vantagem 3')),
                ('benefit3_subtitle', models.CharField(default='Atendimento humanizado', max_length=120, verbose_name='Subtítulo Vantagem 3')),
                ('benefit4_icon', models.CharField(default='solar:box-minimalistic-bold-duotone', max_length=60, verbose_name='Ícone Vantagem 4')),
                ('benefit4_title', models.CharField(default='Loja Física & Envio', max_length=80, verbose_name='Título Vantagem 4')),
                ('benefit4_subtitle', models.CharField(default='Cajazeiras-PB e todo o Brasil', max_length=120, verbose_name='Subtítulo Vantagem 4')),
                ('reviews_active', models.BooleanField(default=True, verbose_name='Exibir Seção de Avaliações Google')),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Configuração da Página Inicial',
                'verbose_name_plural': 'Configurações da Página Inicial',
            },
        ),
        migrations.AddField(
            model_name='carouselslide',
            name='image_mobile',
            field=models.ImageField(blank=True, null=True, upload_to='carousels/mobile/', verbose_name='Imagem Mobile (Opcional - Vertical)'),
        ),
        migrations.AddField(
            model_name='carouselslide',
            name='image_mobile_url',
            field=models.URLField(blank=True, verbose_name='URL da Imagem Mobile (Opcional / CDN)'),
        ),
    ]
