# Generated by Django 6.1 on 2026-09-04 22:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0006_homepageconfig_carouselslide_image_mobile_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomerReview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, verbose_name='Nome do Cliente')),
                ('location', models.CharField(blank=True, default='Cajazeiras - PB', max_length=120, verbose_name='Cidade / Localização')),
                ('rating', models.PositiveSmallIntegerField(default=5, verbose_name='Avaliação (Estrelas)')),
                ('comment', models.TextField(verbose_name='Depoimento / Comentário')),
                ('source', models.CharField(choices=[('google', 'Google Reviews (5.0 ★)'), ('whatsapp', 'WhatsApp & Atendimento'), ('vip', 'Cliente VIP / Provador')], default='google', max_length=20, verbose_name='Origem / Selo')),
                ('avatar', models.ImageField(blank=True, null=True, upload_to='reviews/', verbose_name='Foto / Avatar')),
                ('avatar_url', models.URLField(blank=True, verbose_name='URL da Foto (Opcional)')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Ordem de Exibição')),
                ('is_active', models.BooleanField(default=True, verbose_name='Ativo no Site')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Data do Depoimento')),
            ],
            options={
                'verbose_name': 'Depoimento de Cliente',
                'verbose_name_plural': 'Depoimentos de Clientes',
                'ordering': ['order', '-created_at'],
            },
        ),
        migrations.AlterModelOptions(
            name='linktreeitem',
            options={'ordering': ['page_type', 'order', 'id'], 'verbose_name': 'Item do Linktree', 'verbose_name_plural': 'Itens do Linktree'},
        ),
        migrations.AddField(
            model_name='carouselslide',
            name='button_style',
            field=models.CharField(choices=[('gold', 'Dourado Luxo (Padrão Grife HF)'), ('dark', 'Preto Minimalista'), ('whatsapp', 'Verde WhatsApp'), ('outline', 'Borda Branca')], default='gold', max_length=20, verbose_name='Estilo Visual do Botão'),
        ),
        migrations.AddField(
            model_name='carouselslide',
            name='overlay_darkness',
            field=models.CharField(choices=[('light', 'Leve (25%)'), ('medium', 'Médio (45% - Recomendado)'), ('dark', 'Intenso (70%)')], default='medium', max_length=20, verbose_name='Filtro de Contraste da Foto'),
        ),
        migrations.AddField(
            model_name='carouselslide',
            name='text_alignment',
            field=models.CharField(choices=[('left', 'Alinhado à Esquerda'), ('center', 'Centralizado'), ('right', 'Alinhado à Direita')], default='left', max_length=20, verbose_name='Alinhamento do Texto'),
        ),
        migrations.AddField(
            model_name='homepageconfig',
            name='countdown_active',
            field=models.BooleanField(default=False, verbose_name='Ativar Contador Regressivo'),
        ),
        migrations.AddField(
            model_name='homepageconfig',
            name='countdown_label',
            field=models.CharField(blank=True, default='Lançamento Novo Drop', max_length=120, verbose_name='Texto do Contador'),
        ),
        migrations.AddField(
            model_name='homepageconfig',
            name='countdown_target_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Data/Hora Alvo do Lançamento'),
        ),
        migrations.AddField(
            model_name='homepageconfig',
            name='og_share_description',
            field=models.TextField(blank=True, default='Curadoria exclusiva das marcas mais desejadas do Brasil em Cajazeiras - PB.', verbose_name='Descrição no Compartilhamento'),
        ),
        migrations.AddField(
            model_name='homepageconfig',
            name='og_share_image',
            field=models.ImageField(blank=True, null=True, upload_to='cms/og/', verbose_name='Foto de Prévia no WhatsApp (OpenGraph)'),
        ),
        migrations.AddField(
            model_name='homepageconfig',
            name='og_share_image_url',
            field=models.URLField(blank=True, verbose_name='URL da Foto de Prévia'),
        ),
        migrations.AddField(
            model_name='homepageconfig',
            name='og_share_title',
            field=models.CharField(blank=True, default='Grife HF Multimarcas | Alta Moda Feminina & Masculina', max_length=200, verbose_name='Título no Compartilhamento'),
        ),
        migrations.AddField(
            model_name='homepageconfig',
            name='reviews_subtitle',
            field=models.CharField(blank=True, default='Experiência comprovada por quem veste e confia na curadoria multimarcas da Grife HF.', max_length=200, verbose_name='Subtítulo da Seção de Depoimentos'),
        ),
        migrations.AddField(
            model_name='homepageconfig',
            name='reviews_title',
            field=models.CharField(blank=True, default='O que Nossos Clientes Dizem', max_length=120, verbose_name='Título da Seção de Depoimentos'),
        ),
        migrations.AddField(
            model_name='homepageconfig',
            name='whatsapp_group_active',
            field=models.BooleanField(default=True, verbose_name='Exibir Botão de Grupo VIP'),
        ),
        migrations.AddField(
            model_name='homepageconfig',
            name='whatsapp_group_text',
            field=models.CharField(blank=True, default='Grupo VIP Lançamentos', max_length=100, verbose_name='Texto do Botão VIP'),
        ),
        migrations.AddField(
            model_name='homepageconfig',
            name='whatsapp_group_url',
            field=models.CharField(blank=True, default='https://chat.whatsapp.com/exemplo', max_length=255, verbose_name='Link do Grupo VIP (WhatsApp)'),
        ),
        migrations.AlterField(
            model_name='homepageconfig',
            name='announcement_active',
            field=models.BooleanField(default=True, verbose_name='Exibir Barra Superior'),
        ),
        migrations.AlterField(
            model_name='homepageconfig',
            name='announcement_badge',
            field=models.CharField(blank=True, default='✨ NOVIDADE', max_length=50, verbose_name='Tag da Barra'),
        ),
        migrations.AlterField(
            model_name='homepageconfig',
            name='announcement_link',
            field=models.CharField(blank=True, default='/produtos/', max_length=255, verbose_name='Link do Aviso (Opcional)'),
        ),
        migrations.AlterField(
            model_name='homepageconfig',
            name='announcement_text',
            field=models.CharField(default='Frete Grátis para compras acima de R$ 399 | Entregas expressas em Cajazeiras e região', max_length=255, verbose_name='Texto do Aviso'),
        ),
        migrations.AlterField(
            model_name='homepageconfig',
            name='men_card_image',
            field=models.ImageField(blank=True, null=True, upload_to='home/cards/', verbose_name='Foto Card Masculino'),
        ),
        migrations.AlterField(
            model_name='homepageconfig',
            name='reviews_active',
            field=models.BooleanField(default=True, verbose_name='Exibir Seção de Avaliações'),
        ),
        migrations.AlterField(
            model_name='homepageconfig',
            name='women_card_image',
            field=models.ImageField(blank=True, null=True, upload_to='home/cards/', verbose_name='Foto Card Feminino'),
        ),
        migrations.AlterField(
            model_name='homepageconfig',
            name='women_card_subtitle',
            field=models.TextField(default='Vestidos fluidos, peças em seda pura, alfaiataria premium e conjuntos da Farm Rio e Luiza Fit.', verbose_name='Descrição Card Feminino'),
        ),
        migrations.AlterField(
            model_name='homepageconfig',
            name='women_card_title',
            field=models.CharField(default='Moda Feminina Autoral', max_length=120, verbose_name='Título Card Feminino'),
        ),
        migrations.AlterField(
            model_name='linktreeitem',
            name='clicks_count',
            field=models.PositiveIntegerField(default=0, verbose_name='Cliques Registrados'),
        ),
        migrations.AlterField(
            model_name='linktreeitem',
            name='icon',
            field=models.CharField(default='bx bx-link-external', help_text='Ex: bx bxl-whatsapp, bx bx-store-alt, bx bxl-instagram', max_length=50, verbose_name='Ícone Boxicons'),
        ),
        migrations.AlterField(
            model_name='linktreeitem',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Ativo na Página'),
        ),
        migrations.AlterField(
            model_name='linktreeitem',
            name='is_highlighted',
            field=models.BooleanField(default=False, verbose_name='Botão em Destaque (Pulsar)'),
        ),
        migrations.AlterField(
            model_name='linktreeitem',
            name='order',
            field=models.PositiveIntegerField(default=0, verbose_name='Ordem'),
        ),
        migrations.AlterField(
            model_name='linktreeitem',
            name='page_type',
            field=models.CharField(choices=[('grife_hf', 'Grife HF Multimarcas (/links)'), ('luiza_fit', 'Luiza Fit Moda Fitness (/tree)')], default='grife_hf', max_length=20, verbose_name='Página de Destino'),
        ),
        migrations.AlterField(
            model_name='linktreeitem',
            name='style',
            field=models.CharField(default='outline', help_text='primary, success, dark, gold, rose, champagne, outline', max_length=30, verbose_name='Estilo do Botão'),
        ),
        migrations.AlterField(
            model_name='linktreeitem',
            name='subtitle',
            field=models.CharField(blank=True, max_length=200, verbose_name='Subtítulo / Descrição Rápida'),
        ),
        migrations.AlterField(
            model_name='linktreeitem',
            name='url',
            field=models.CharField(max_length=500, verbose_name='Link de Redirecionamento'),
        ),
    ]
