# Generated by Django 6.1 on 2026-09-04 23:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0007_customerreview_alter_linktreeitem_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customerreview',
            name='source',
            field=models.CharField(choices=[('instagram', 'Instagram Direct / Story'), ('google', 'Google Reviews (5.0 ★)'), ('whatsapp', 'WhatsApp & Atendimento'), ('vip', 'Cliente VIP / Provador'), ('direct', 'Direct / Mensagem Privada'), ('loja', 'Loja Física (Cajazeiras - PB)'), ('outro', 'Cliente Verificado / Indicação')], default='google', max_length=20, verbose_name='Origem / Selo'),
        ),
    ]
