# Generated by Django 6.1 on 2026-09-04 23:24

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0008_alter_customerreview_source'),
    ]

    operations = [
        migrations.AddField(
            model_name='homepageconfig',
            name='store_hours_text',
            field=models.CharField(blank=True, default='Segunda a Sexta: 08h às 18h • Sábado: 08h às 13h', max_length=150, verbose_name='Texto Resumo do Horário'),
        ),
        migrations.AddField(
            model_name='homepageconfig',
            name='store_saturday_active',
            field=models.BooleanField(default=True, verbose_name='Abre aos Sábados'),
        ),
        migrations.AddField(
            model_name='homepageconfig',
            name='store_saturday_close',
            field=models.TimeField(default=datetime.time(13, 0), verbose_name='Sábado - Fechamento'),
        ),
        migrations.AddField(
            model_name='homepageconfig',
            name='store_saturday_open',
            field=models.TimeField(default=datetime.time(8, 0), verbose_name='Sábado - Abertura'),
        ),
        migrations.AddField(
            model_name='homepageconfig',
            name='store_status_mode',
            field=models.CharField(choices=[('auto', '🟢 Automático pelo Horário de Funcionamento'), ('open', '🟢 Forçar Aberto'), ('closed', '🔴 Forçar Fechado'), ('manual', '✏️ Texto Manual Fixo')], default='auto', max_length=20, verbose_name='Modo do Selo de Status'),
        ),
        migrations.AddField(
            model_name='homepageconfig',
            name='store_sunday_active',
            field=models.BooleanField(default=False, verbose_name='Abre aos Domingos / Feriados'),
        ),
        migrations.AddField(
            model_name='homepageconfig',
            name='store_sunday_close',
            field=models.TimeField(blank=True, null=True, verbose_name='Domingo - Fechamento'),
        ),
        migrations.AddField(
            model_name='homepageconfig',
            name='store_sunday_open',
            field=models.TimeField(blank=True, null=True, verbose_name='Domingo - Abertura'),
        ),
        migrations.AddField(
            model_name='homepageconfig',
            name='store_weekday_close',
            field=models.TimeField(default=datetime.time(18, 0), verbose_name='Seg a Sex - Fechamento'),
        ),
        migrations.AddField(
            model_name='homepageconfig',
            name='store_weekday_open',
            field=models.TimeField(default=datetime.time(8, 0), verbose_name='Seg a Sex - Abertura'),
        ),
        migrations.AlterField(
            model_name='homepageconfig',
            name='store_status_badge',
            field=models.CharField(blank=True, default='Loja Aberta', max_length=100, verbose_name='Badge de Status / Texto Manual'),
        ),
    ]
