# Generated by Django 6.1 on 2026-09-05 18:51

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0009_homepageconfig_store_hours_text_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='StockMovement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('movement_type', models.CharField(choices=[('IN', 'Entrada (+)'), ('OUT', 'Saída (-)'), ('ADJUST', 'Ajuste de Saldo (=)')], max_length=10, verbose_name='Tipo de Movimento')),
                ('reason', models.CharField(choices=[('purchase', 'Compra / Reposição de Fornecedor'), ('return_customer', 'Devolução de Cliente'), ('drop_launch', 'Novo Drop / Lançamento'), ('initial_stock', 'Saldo Inicial / Cadastro'), ('sale', 'Venda'), ('showroom', 'Mostruário / Provador / Fotos'), ('damaged', 'Avaria / Defeito'), ('loss', 'Perda / Extravio'), ('gift_pr', 'Brinde / Parceria / Influenciador'), ('return_supplier', 'Devolução para Fornecedor'), ('inventory_audit', 'Ajuste de Balanço / Inventário'), ('other', 'Outro Motivo')], default='purchase', max_length=30, verbose_name='Motivo')),
                ('quantity', models.IntegerField(verbose_name='Quantidade Movimentada')),
                ('previous_stock', models.IntegerField(default=0, verbose_name='Estoque Anterior')),
                ('new_stock', models.IntegerField(default=0, verbose_name='Novo Estoque')),
                ('cost_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Custo Unitário (R$)')),
                ('invoice_number', models.CharField(blank=True, max_length=100, verbose_name='Nota Fiscal / Pedido / Doc')),
                ('notes', models.TextField(blank=True, verbose_name='Observações')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Data da Movimentação')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='stock_movements', to=settings.AUTH_USER_MODEL, verbose_name='Registrado por')),
                ('variant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stock_movements', to='catalog.productvariant', verbose_name='Variante do Produto')),
            ],
            options={
                'verbose_name': 'Movimentação de Estoque',
                'verbose_name_plural': 'Movimentações de Estoque',
                'ordering': ['-created_at'],
            },
        ),
    ]
