# Generated by Django 6.1 on 2026-09-05 20:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0010_stockmovement'),
    ]

    operations = [
        migrations.AddField(
            model_name='homepageconfig',
            name='promo_active',
            field=models.BooleanField(default=True, verbose_name='Ativar Bloco de Promoções & Timer'),
        ),
        migrations.AddField(
            model_name='homepageconfig',
            name='promo_badge',
            field=models.CharField(blank=True, default='⚡ DROP RELÂMPAGO DE 48 HORAS', max_length=100, verbose_name='Tag da Promoção'),
        ),
        migrations.AddField(
            model_name='homepageconfig',
            name='promo_button_text',
            field=models.CharField(blank=True, default='Garantir Oferta no WhatsApp', max_length=80, verbose_name='Texto do Botão Promocional'),
        ),
        migrations.AddField(
            model_name='homepageconfig',
            name='promo_button_url',
            field=models.CharField(blank=True, default='/produtos/?gender=F', max_length=255, verbose_name='Link do Botão'),
        ),
        migrations.AddField(
            model_name='homepageconfig',
            name='promo_card_image',
            field=models.ImageField(blank=True, null=True, upload_to='home/promo/', verbose_name='Foto do Card Promocional'),
        ),
        migrations.AddField(
            model_name='homepageconfig',
            name='promo_card_image_url',
            field=models.URLField(blank=True, default='https://images.unsplash.com/photo-1490481651871-ab68de25d43d?auto=format&fit=crop&w=1000&q=80', verbose_name='URL da Foto Promocional (Fallback/CDN)'),
        ),
        migrations.AddField(
            model_name='homepageconfig',
            name='promo_discount_badge',
            field=models.CharField(blank=True, default='-30% OFF', max_length=50, verbose_name='Tag de Desconto'),
        ),
        migrations.AddField(
            model_name='homepageconfig',
            name='promo_end_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Data/Hora de Término do Timer'),
        ),
        migrations.AddField(
            model_name='homepageconfig',
            name='promo_stock_alert_text',
            field=models.CharField(blank=True, default='⚠️ Últimas unidades disponíveis na loja física', max_length=150, verbose_name='Alerta de Estoque / Escassez'),
        ),
        migrations.AddField(
            model_name='homepageconfig',
            name='promo_subtitle',
            field=models.TextField(blank=True, default='Condições exclusivas por tempo limitado. Aproveite a contagem regressiva para garantir sua numeração.', verbose_name='Subtítulo da Promoção'),
        ),
        migrations.AddField(
            model_name='homepageconfig',
            name='promo_title',
            field=models.CharField(blank=True, default='Peças Selecionadas com até 30% OFF', max_length=150, verbose_name='Título da Promoção'),
        ),
        migrations.AddField(
            model_name='homepageconfig',
            name='promo_top_ticker_active',
            field=models.BooleanField(default=True, verbose_name='Exibir Barra Fixa no Topo com Timer'),
        ),
    ]
