# Generated by Django 5.1.15 on 2026-09-07 07:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0011_homepageconfig_promo_active_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customerreview',
            name='source',
            field=models.CharField(choices=[('instagram', 'Instagram Direct / Story'), ('google', 'Google Reviews (5.0 ★)'), ('whatsapp', 'WhatsApp & Atendimento'), ('vip', 'Cliente VIP / Provador'), ('direct', 'Direct / Mensagem Privada'), ('loja', 'Espaço Físico (Sítio Histórico de Olinda)'), ('outro', 'Cliente Verificado / Indicação')], default='google', max_length=20, verbose_name='Origem / Selo'),
        ),
    ]
