# Generated by Django 6.1 on 2026-09-04 14:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0003_productimage_color'),
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductReservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_name', models.CharField(max_length=150, verbose_name='Nome do Cliente')),
                ('customer_phone', models.CharField(max_length=30, verbose_name='WhatsApp / Telefone')),
                ('color', models.CharField(blank=True, max_length=50, verbose_name='Cor Desejada')),
                ('size', models.CharField(blank=True, max_length=30, verbose_name='Tamanho Desejado')),
                ('notes', models.TextField(blank=True, verbose_name='Observações')),
                ('status', models.CharField(choices=[('pending', 'Pendente (Aguardando Chegada)'), ('notified', 'Cliente Avisado'), ('converted', 'Venda Concluída'), ('cancelled', 'Cancelado / Desistiu')], default='pending', max_length=20, verbose_name='Status')),
                ('notified_at', models.DateTimeField(blank=True, null=True, verbose_name='Avisado em')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Data da Reserva')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Última Atualização')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reservations', to='catalog.product', verbose_name='Peça')),
            ],
            options={
                'verbose_name': 'Reserva / Fila de Espera',
                'verbose_name_plural': 'Reservas / Fila de Espera',
                'ordering': ['-created_at'],
            },
        ),
    ]
