# Generated by Django 6.1 on 2026-09-04 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_productreservation'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='delivery_method',
            field=models.CharField(choices=[('pickup', 'Retirada na Loja'), ('motoboy', 'Entrega Rápida (Motoboy Cajazeiras)'), ('shipping', 'Envio Correios / Transportadora (Brasil)')], default='pickup', max_length=30, verbose_name='Forma de Entrega'),
        ),
        migrations.AddField(
            model_name='order',
            name='origin',
            field=models.CharField(choices=[('store_online', 'Loja Online'), ('whatsapp', 'WhatsApp VIP'), ('counter', 'Balcão / Loja Física')], default='store_online', max_length=30, verbose_name='Origem do Pedido'),
        ),
        migrations.AddField(
            model_name='order',
            name='payment_method',
            field=models.CharField(choices=[('pix', 'Pix (Envio Imediato)'), ('credit_card', 'Cartão de Crédito (até 12x)'), ('debit_card', 'Cartão de Débito'), ('cash', 'Dinheiro / Espécie'), ('on_delivery', 'Pagamento na Entrega')], default='pix', max_length=30, verbose_name='Forma de Pagamento'),
        ),
    ]
