# Generated by Django 5.1.15 on 2026-09-07 07:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0012_alter_customerreview_source'),
        ('orders', '0003_order_delivery_method_order_origin_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_name', models.CharField(max_length=150, verbose_name='Nome do Cliente')),
                ('customer_phone', models.CharField(max_length=30, verbose_name='WhatsApp / Telefone')),
                ('customer_email', models.EmailField(blank=True, max_length=254, verbose_name='E-mail')),
                ('appointment_date', models.DateField(verbose_name='Data do Agendamento')),
                ('appointment_time', models.CharField(max_length=10, verbose_name='Horário')),
                ('professional', models.CharField(default='Cabeleireiro Eduardo Cardoso (Barbeiro Vaka)', max_length=100, verbose_name='Profissional')),
                ('total_price', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Valor Estimado (R$)')),
                ('notes', models.TextField(blank=True, verbose_name='Observações / Preferências')),
                ('status', models.CharField(choices=[('pending', 'Pendente'), ('confirmed', 'Confirmado'), ('completed', 'Concluído'), ('cancelled', 'Cancelado')], default='pending', max_length=20, verbose_name='Status')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('services', models.ManyToManyField(related_name='appointments', to='catalog.product', verbose_name='Procedimentos / Serviços')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='appointments', to=settings.AUTH_USER_MODEL, verbose_name='Usuário')),
            ],
            options={
                'verbose_name': 'Agendamento',
                'verbose_name_plural': 'Agendamentos',
                'ordering': ['-appointment_date', '-appointment_time'],
            },
        ),
    ]
